### PR TITLE
Add Each() method for validating iterables.

### PR DESCRIPTION
**Pull request by petervandenbroek**
I was really missing the ability to validate on arrays or maps, so I've added the Each() method that was mentioned in https://github.com/go-ozzo/ozzo-validation/issues/55.

I've tried to test is as thoroughly as possible.

### CODE REVIEW

**Comment by petervandenbroek** [comment]
The checks fail because I've used a reflect method called Value.MapRange(), which was added in Go 1.12.
Do you want me to replace the method with something else?

**Comment by qiangxue** [comment]
Looks great to me! Thanks!
Could you please update README accordingly? https://github.com/go-ozzo/ozzo-validation#mapsslicesarrays-of-validatables

**Comment by petervandenbroek** [comment]
Updated the README, I hope it's clear enough.

**Comment by qiangxue** [comment]
Great work! Thank you for your contribution!

**Comment by SebastianM** [comment]
@petervandenbroek seems like InternalError cases are broken. When a return an InternalError in an Each validator, the error isn't an InternalError as the whole result of the struct validation. Do you have time to work on a fix?

**Comment by NathanBaulch** [comment]
I just noticed this problem too @qiangxue. `Each.ValidateWithContext` and `EnsureString` (in util.go) return basic `errors.New` errors that don't implement either `validation.Error` or `validation.InternalError`.

**Comment by delfick** [comment]
Hi, it seems this line https://github.com/go-ozzo/ozzo-validation/blob/master/each.go#L81 means that we end up passing around the value being pointed at rather than the pointer itself, resulting in a copy of it. Which isn't great when it has a mutex on it, like a protobuf object.

**Comment by delfick** [comment]
Hi, it seems this line https://github.com/go-ozzo/ozzo-validation/blob/master/each.go#L81 means that we end up passing around the value being pointed at rather than the pointer itself, resulting in a copy of it. Which isn't great when it has a mutex on it, like a protobuf object.

**Pull request merged**
