### PR TITLE
fix(README): update GoDoc link to v4's

### PR DESCRIPTION
**Pull request by mrg0lden**
As the title states, the change is so tiny

### CODE REVIEW

**Comment by qiangxue** [comment]
Unfortunately, adding `/v4` results in 404 error.

**Comment by mrg0lden** [comment]
Strange, but the current link takes me always to version 3's pkg.go.dev. I didn't check it out but now, since I had GoDoc set to redirect me automatically to pkg.go.dev.

Would it be okay if I put a pkg.go.dev badge instead of GoDoc's? @qiangxue

**Comment by qiangxue** [comment]
The version displayed on pkg.go.dev doesn't seem to be up to date (it shows v3.6.0+) while GoDoc shows the latest version. So I think we should stick to the current link.

**Comment by mrg0lden** [comment]
@qiangxue yup, pkg.go.dev shows version 3.6 with the current link, but when you add /v4 it shows the latest version's docs

**Comment by qiangxue** [comment]
Well, since the problem is caused by your particular auto-redirection configuration, I don't think we should fix anything (because GoDoc link is correct as is). It's also strange why pkg.go.dev would require `/v4` in order to display the latest doc.

**Comment by mrg0lden** [comment]
Well, it's kinda particular since it's not the default behavior, shall I report that to the Go team instead?

**Comment by qiangxue** [comment]
I think so. It doesn't seem reasonable to me that the URL without the version number displays a version in the middle.

**Comment by mrg0lden** [comment]
I think pkg.go.dev follows the module import link, since version 3 doesn't support modules it has the default repo link, while v4 supports Go modules with the module link being the same with /v4 suffix.

**Pull request closed without merging**
