### PR TITLE
validation rule: min: fix error message

### PR DESCRIPTION
**Pull request by omeid**

### CODE REVIEW

**Comment by qiangxue** [comment]
Could you fix the test error as well? Thanks!

**Comment by omeid** [comment]
No worries, I just looked and the Max rule needs more consideration. I will create a pull request soon.

**Comment by qiangxue** [comment]
Fixed in https://github.com/go-ozzo/ozzo-validation/commit/86433d65440f530b10e94b1b1920895f08b22ec5.

**Comment by omeid** [comment]
Thanks for the fix! Sorry, I have been rather busy to wrap this up.

**Pull request closed without merging**
